// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `from`, `from`

Future<void> wrapstatuscode({required WrapStatusCode a}) =>
    RustLib.instance.api.crateApiTypesStatusCodeWrapstatuscode(a: a);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WrapStatusCode>>
abstract class WrapStatusCode implements RustOpaqueInterface {
  String description();

  static WrapStatusCode? fromStr(String s) =>
      RustLib.instance.api.crateApiTypesStatusCodeWrapStatusCodeFromStr(s: s);

  static WrapStatusCode? fromU32(int code) => RustLib.instance.api
      .crateApiTypesStatusCodeWrapStatusCodeFromU32(code: code);

  String name();
}
