// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'byte_string.dart';
import 'date_time.dart';
import 'guid.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'status_code.dart';
import 'string.dart';
part 'variant.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

Future<void> wrapvariant({required WrapVariant a}) =>
    RustLib.instance.api.crateApiTypesVariantWrapvariant(a: a);

@freezed
sealed class WrapVariant with _$WrapVariant {
  const WrapVariant._();

  /// Empty type has no value. It is equivalent to a Null value (part 6 5.1.6)
  const factory WrapVariant.empty() = WrapVariant_Empty;

  /// Boolean
  const factory WrapVariant.boolean(
    bool field0,
  ) = WrapVariant_Boolean;

  /// Signed byte
  const factory WrapVariant.sByte(
    int field0,
  ) = WrapVariant_SByte;

  /// Unsigned byte
  const factory WrapVariant.byte(
    int field0,
  ) = WrapVariant_Byte;

  /// Signed 16-bit int
  const factory WrapVariant.int16(
    int field0,
  ) = WrapVariant_Int16;

  /// Unsigned 16-bit int
  const factory WrapVariant.uInt16(
    int field0,
  ) = WrapVariant_UInt16;

  /// Signed 32-bit int
  const factory WrapVariant.int32(
    int field0,
  ) = WrapVariant_Int32;

  /// Unsigned 32-bit int
  const factory WrapVariant.uInt32(
    int field0,
  ) = WrapVariant_UInt32;

  /// Signed 64-bit int
  const factory WrapVariant.int64(
    PlatformInt64 field0,
  ) = WrapVariant_Int64;

  /// Unsigned 64-bit int
  const factory WrapVariant.uInt64(
    BigInt field0,
  ) = WrapVariant_UInt64;

  /// Float
  const factory WrapVariant.float(
    double field0,
  ) = WrapVariant_Float;

  /// Double
  const factory WrapVariant.double(
    double field0,
  ) = WrapVariant_Double;

  /// String
  const factory WrapVariant.string(
    WrapUaString field0,
  ) = WrapVariant_String;

  /// DateTime
  const factory WrapVariant.dateTime(
    BoxWrapDateTime field0,
  ) = WrapVariant_DateTime;

  /// Guid
  const factory WrapVariant.guid(
    BoxWrapGuid field0,
  ) = WrapVariant_Guid;

  /// StatusCode
  const factory WrapVariant.statusCode(
    WrapStatusCode field0,
  ) = WrapVariant_StatusCode;

  /// ByteString
  const factory WrapVariant.byteString(
    WrapByteString field0,
  ) = WrapVariant_ByteString;

  /// XmlElement
  const factory WrapVariant.xmlElement(
    WrapUaString field0,
  ) = WrapVariant_XmlElement;
}
