// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `substring`, `value`
// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `substring_nonvoid`, `value_copy`

Future<void> wrapwritevalue({required WriteValue a}) =>
    RustLib.instance.api.crateApiTypesWriteValueWrapwritevalue(a: a);

Future<void> wrapnodeid({required NodeId a}) =>
    RustLib.instance.api.crateApiTypesWriteValueWrapnodeid(a: a);

Future<void> wrapidetifier({required Identifier a}) =>
    RustLib.instance.api.crateApiTypesWriteValueWrapidetifier(a: a);

Future<void> wrapguid({required Guid a}) =>
    RustLib.instance.api.crateApiTypesWriteValueWrapguid(a: a);

Future<void> wrapbytestring({required ByteString a}) =>
    RustLib.instance.api.crateApiTypesWriteValueWrapbytestring(a: a);

Future<void> wrapuastring({required UaString a}) =>
    RustLib.instance.api.crateApiTypesWriteValueWrapuastring(a: a);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Identifier>>
abstract class Identifier implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NodeId>>
abstract class NodeId implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WriteValue>>
abstract class WriteValue implements RustOpaqueInterface {}

abstract class CustomUAStringFunctions {
  UaString? substringNonvoid({required BigInt min, required BigInt max});

  String? valueCopy();
}
